import {
  AlarmClock,
  Aperture,
  Apple,
  Archive,
  Banknote,
  Bike,
  Binary,
  Blocks,
  BookOpen,
  Bookmark,
  Bot,
  Braces,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChartNoAxesCombined,
  CircuitBoard,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  Code2,
  Coffee,
  Compass,
  Contact,
  CookingPot,
  Cpu,
  CreditCard,
  CupSoda,
  Database,
  Dumbbell,
  FileCode2,
  FileText,
  Film,
  Flag,
  Flower2,
  Folder,
  Gamepad2,
  Gift,
  GitBranch,
  GitPullRequest,
  Globe2,
  GraduationCap,
  Headphones,
  Heart,
  Image,
  Inbox,
  Key,
  Languages,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  Link,
  ListTodo,
  Lock,
  Mail,
  Map as MapIcon,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Mic,
  MonitorPlay,
  Moon,
  Mountain,
  Music,
  Newspaper,
  NotebookPen,
  Package,
  Palette,
  Pencil,
  PenTool,
  Phone,
  Pin,
  Plane,
  Presentation,
  Radio,
  Receipt,
  Ruler,
  School,
  Search,
  Send,
  Server,
  Shapes,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  StickyNote,
  Store,
  Sun,
  Tent,
  Terminal,
  TrainFront,
  TreePine,
  UserRound,
  Users,
  Utensils,
  Video,
  Wallet,
  Wifi,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type FolderIconOption = {
  id: string;
  label: string;
  group: string;
  keywords: string;
  Icon: LucideIcon;
};

export const folderIconGroups = [
  "常用图标",
  "开发科技",
  "设计媒体",
  "学习效率",
  "工作沟通",
  "生活兴趣",
];

export const folderIcons: FolderIconOption[] = [
  { id: "Folder", label: "文件夹", group: "常用图标", keywords: "目录 分类 默认 folder directory", Icon: Folder },
  { id: "Bookmark", label: "书签", group: "常用图标", keywords: "收藏 保存 bookmark save", Icon: Bookmark },
  { id: "Star", label: "星标", group: "常用图标", keywords: "星星 收藏 喜欢 star favorite", Icon: Star },
  { id: "Heart", label: "心愿", group: "常用图标", keywords: "爱心 喜爱 收藏 heart love wishlist", Icon: Heart },
  { id: "Pin", label: "图钉", group: "常用图标", keywords: "置顶 固定 pin top", Icon: Pin },
  { id: "Inbox", label: "收件箱", group: "常用图标", keywords: "待整理 收集 inbox collect", Icon: Inbox },
  { id: "Archive", label: "归档", group: "常用图标", keywords: "存档 箱子 archive storage", Icon: Archive },
  { id: "Link", label: "链接", group: "常用图标", keywords: "网址 网站 link url website", Icon: Link },
  { id: "Globe2", label: "地球", group: "常用图标", keywords: "全球 网络 世界 globe earth web", Icon: Globe2 },
  { id: "Compass", label: "探索", group: "常用图标", keywords: "发现 指南针 导航 compass explore discovery", Icon: Compass },
  { id: "Flag", label: "旗帜", group: "常用图标", keywords: "目标 标记 里程碑 flag goal milestone", Icon: Flag },
  { id: "Map", label: "地图", group: "常用图标", keywords: "路线 位置 导航 map route location", Icon: MapIcon },
  { id: "Sparkles", label: "灵感", group: "常用图标", keywords: "星光 智能 人工智能 AI sparkles inspiration", Icon: Sparkles },
  { id: "Zap", label: "闪电", group: "常用图标", keywords: "效率 快捷 能量 zap lightning productivity", Icon: Zap },
  { id: "Gift", label: "礼物", group: "常用图标", keywords: "惊喜 推荐 福利 gift present", Icon: Gift },
  { id: "Key", label: "钥匙", group: "常用图标", keywords: "账号 密码 密钥 key account password", Icon: Key },
  { id: "Shield", label: "安全", group: "常用图标", keywords: "盾牌 防护 隐私 shield security privacy", Icon: Shield },
  { id: "Lock", label: "私密", group: "常用图标", keywords: "锁 保密 加密 lock private encryption", Icon: Lock },

  { id: "Code2", label: "代码", group: "开发科技", keywords: "编程 开发 程序 code programming development", Icon: Code2 },
  { id: "Terminal", label: "终端", group: "开发科技", keywords: "命令行 脚本 terminal shell cli", Icon: Terminal },
  { id: "Braces", label: "接口", group: "开发科技", keywords: "括号 数据 格式 braces json api", Icon: Braces },
  { id: "FileCode2", label: "源码", group: "开发科技", keywords: "代码文件 文档 file code source", Icon: FileCode2 },
  { id: "Binary", label: "算法", group: "开发科技", keywords: "二进制 计算 数据结构 binary algorithm", Icon: Binary },
  { id: "Bug", label: "调试", group: "开发科技", keywords: "测试 缺陷 排错 bug debug test", Icon: Bug },
  { id: "GitBranch", label: "分支", group: "开发科技", keywords: "版本控制 仓库 git branch repository github", Icon: GitBranch },
  { id: "GitPullRequest", label: "代码审查", group: "开发科技", keywords: "合并 请求 协作 git pull request review", Icon: GitPullRequest },
  { id: "Database", label: "数据库", group: "开发科技", keywords: "数据 存储 database sql storage", Icon: Database },
  { id: "Server", label: "服务器", group: "开发科技", keywords: "主机 运维 后端 server host backend", Icon: Server },
  { id: "Cpu", label: "芯片", group: "开发科技", keywords: "处理器 硬件 计算机 cpu chip hardware", Icon: Cpu },
  { id: "CircuitBoard", label: "电路", group: "开发科技", keywords: "电子 嵌入式 电路板 circuit electronics embedded", Icon: CircuitBoard },
  { id: "Cloud", label: "云服务", group: "开发科技", keywords: "云端 云盘 部署 cloud hosting deploy", Icon: Cloud },
  { id: "Wifi", label: "网络", group: "开发科技", keywords: "无线 路由 连接 wifi network wireless", Icon: Wifi },
  { id: "Bot", label: "机器人", group: "开发科技", keywords: "人工智能 助手 模型 bot robot AI agent", Icon: Bot },
  { id: "Workflow", label: "工作流", group: "开发科技", keywords: "自动化 流程 编排 workflow automation", Icon: Workflow },
  { id: "Blocks", label: "组件", group: "开发科技", keywords: "积木 模块 框架 blocks component framework", Icon: Blocks },
  { id: "Package", label: "软件包", group: "开发科技", keywords: "依赖 包管理 工具 package dependency npm", Icon: Package },

  { id: "Palette", label: "调色盘", group: "设计媒体", keywords: "设计 颜色 配色 palette design color", Icon: Palette },
  { id: "Brush", label: "画笔", group: "设计媒体", keywords: "绘画 插画 美术 brush painting art", Icon: Brush },
  { id: "PenTool", label: "钢笔", group: "设计媒体", keywords: "矢量 路径 设计 pen vector design", Icon: PenTool },
  { id: "Pencil", label: "铅笔", group: "设计媒体", keywords: "编辑 草稿 创作 pencil edit sketch", Icon: Pencil },
  { id: "Ruler", label: "尺子", group: "设计媒体", keywords: "尺寸 测量 布局 ruler measure layout", Icon: Ruler },
  { id: "Shapes", label: "形状", group: "设计媒体", keywords: "几何 图形 素材 shapes geometry graphics", Icon: Shapes },
  { id: "Layers", label: "图层", group: "设计媒体", keywords: "叠加 层级 设计 layers stack design", Icon: Layers },
  { id: "Image", label: "图片", group: "设计媒体", keywords: "照片 图库 壁纸 image photo wallpaper", Icon: Image },
  { id: "Camera", label: "相机", group: "设计媒体", keywords: "摄影 拍照 camera photography", Icon: Camera },
  { id: "Aperture", label: "镜头", group: "设计媒体", keywords: "光圈 摄影 滤镜 aperture lens photography", Icon: Aperture },
  { id: "Video", label: "视频", group: "设计媒体", keywords: "录像 直播 视频会议 video recording live", Icon: Video },
  { id: "Film", label: "胶片", group: "设计媒体", keywords: "电影 影视 影片 film movie cinema", Icon: Film },
  { id: "Clapperboard", label: "拍摄", group: "设计媒体", keywords: "场记 剪辑 制片 clapperboard editing production", Icon: Clapperboard },
  { id: "Music", label: "音乐", group: "设计媒体", keywords: "歌曲 音符 乐谱 music song audio", Icon: Music },
  { id: "Headphones", label: "耳机", group: "设计媒体", keywords: "音频 听歌 播客 headphones listening podcast", Icon: Headphones },
  { id: "Mic", label: "麦克风", group: "设计媒体", keywords: "录音 配音 播客 mic voice podcast", Icon: Mic },
  { id: "Radio", label: "电台", group: "设计媒体", keywords: "广播 音频 频道 radio broadcast channel", Icon: Radio },
  { id: "MonitorPlay", label: "播放器", group: "设计媒体", keywords: "影视 屏幕 流媒体 monitor play streaming", Icon: MonitorPlay },

  { id: "BookOpen", label: "阅读", group: "学习效率", keywords: "书本 读书 学习 book reading learning", Icon: BookOpen },
  { id: "Library", label: "图书馆", group: "学习效率", keywords: "书架 文库 资料 library books collection", Icon: Library },
  { id: "GraduationCap", label: "学术", group: "学习效率", keywords: "毕业 教育 论文 graduation education academic", Icon: GraduationCap },
  { id: "School", label: "学校", group: "学习效率", keywords: "校园 课程 教育 school campus course", Icon: School },
  { id: "NotebookPen", label: "笔记", group: "学习效率", keywords: "记录 手帐 写作 notebook notes writing", Icon: NotebookPen },
  { id: "FileText", label: "文档", group: "学习效率", keywords: "文章 文件 资料 file text document", Icon: FileText },
  { id: "StickyNote", label: "便签", group: "学习效率", keywords: "备忘 提醒 记录 sticky note memo", Icon: StickyNote },
  { id: "ClipboardList", label: "清单", group: "学习效率", keywords: "检查 列表 计划 clipboard list checklist", Icon: ClipboardList },
  { id: "ListTodo", label: "待办", group: "学习效率", keywords: "任务 完成 计划 todo task plan", Icon: ListTodo },
  { id: "Calendar", label: "日历", group: "学习效率", keywords: "日期 日程 安排 calendar date schedule", Icon: Calendar },
  { id: "Clock", label: "时间", group: "学习效率", keywords: "时钟 历史 效率 clock time history", Icon: Clock },
  { id: "AlarmClock", label: "闹钟", group: "学习效率", keywords: "提醒 计时 专注 alarm timer focus", Icon: AlarmClock },
  { id: "Search", label: "检索", group: "学习效率", keywords: "搜索 研究 查找 search research find", Icon: Search },
  { id: "Calculator", label: "计算器", group: "学习效率", keywords: "数学 计算 数字 calculator math number", Icon: Calculator },
  { id: "ChartNoAxesCombined", label: "图表", group: "学习效率", keywords: "统计 数据 分析 chart statistics analytics", Icon: ChartNoAxesCombined },
  { id: "Presentation", label: "演示", group: "学习效率", keywords: "幻灯片 课件 汇报 presentation slides ppt", Icon: Presentation },
  { id: "Languages", label: "语言", group: "学习效率", keywords: "翻译 外语 英语 languages translation english", Icon: Languages },
  { id: "Lightbulb", label: "点子", group: "学习效率", keywords: "灵感 创意 思考 lightbulb idea inspiration", Icon: Lightbulb },

  { id: "Briefcase", label: "工作", group: "工作沟通", keywords: "公文包 职业 办公 briefcase work career", Icon: Briefcase },
  { id: "Building2", label: "公司", group: "工作沟通", keywords: "企业 办公楼 组织 building company business", Icon: Building2 },
  { id: "Users", label: "团队", group: "工作沟通", keywords: "用户 协作 社群 users team community", Icon: Users },
  { id: "UserRound", label: "个人", group: "工作沟通", keywords: "用户 账号 主页 user person profile", Icon: UserRound },
  { id: "Contact", label: "通讯录", group: "工作沟通", keywords: "联系人 名片 人脉 contact address connections", Icon: Contact },
  { id: "Mail", label: "邮件", group: "工作沟通", keywords: "信封 邮箱 通讯 mail email letter", Icon: Mail },
  { id: "Send", label: "发送", group: "工作沟通", keywords: "纸飞机 分享 发布 send share publish", Icon: Send },
  { id: "MessageCircle", label: "聊天", group: "工作沟通", keywords: "消息 对话 评论 message chat comment", Icon: MessageCircle },
  { id: "MessagesSquare", label: "讨论", group: "工作沟通", keywords: "论坛 交流 群聊 messages forum discussion", Icon: MessagesSquare },
  { id: "Phone", label: "电话", group: "工作沟通", keywords: "联系 通话 客服 phone call support", Icon: Phone },
  { id: "Megaphone", label: "公告", group: "工作沟通", keywords: "推广 营销 通知 megaphone marketing announcement", Icon: Megaphone },
  { id: "Newspaper", label: "资讯", group: "工作沟通", keywords: "新闻 报纸 阅读 newspaper news feed", Icon: Newspaper },
  { id: "Wallet", label: "钱包", group: "工作沟通", keywords: "财务 理财 资产 wallet finance money", Icon: Wallet },
  { id: "CreditCard", label: "银行卡", group: "工作沟通", keywords: "信用卡 支付 账单 credit card payment", Icon: CreditCard },
  { id: "Banknote", label: "现金", group: "工作沟通", keywords: "货币 金融 投资 banknote cash investment", Icon: Banknote },
  { id: "ShoppingCart", label: "购物", group: "工作沟通", keywords: "购物车 电商 采购 shopping cart ecommerce", Icon: ShoppingCart },
  { id: "Store", label: "商店", group: "工作沟通", keywords: "店铺 商城 零售 store shop retail", Icon: Store },
  { id: "Receipt", label: "账单", group: "工作沟通", keywords: "收据 发票 记账 receipt invoice accounting", Icon: Receipt },

  { id: "Coffee", label: "咖啡", group: "生活兴趣", keywords: "生活 休闲 饮品 coffee cafe lifestyle", Icon: Coffee },
  { id: "CupSoda", label: "饮料", group: "生活兴趣", keywords: "汽水 奶茶 果汁 cup soda drink", Icon: CupSoda },
  { id: "CookingPot", label: "烹饪", group: "生活兴趣", keywords: "做饭 厨房 食谱 cooking pot recipe", Icon: CookingPot },
  { id: "Utensils", label: "美食", group: "生活兴趣", keywords: "餐饮 餐厅 吃饭 utensils food restaurant", Icon: Utensils },
  { id: "Apple", label: "水果", group: "生活兴趣", keywords: "苹果 营养 健康 apple fruit nutrition", Icon: Apple },
  { id: "Leaf", label: "绿叶", group: "生活兴趣", keywords: "自然 环保 植物 leaf nature ecology", Icon: Leaf },
  { id: "TreePine", label: "森林", group: "生活兴趣", keywords: "松树 树木 户外 tree pine forest", Icon: TreePine },
  { id: "Flower2", label: "花朵", group: "生活兴趣", keywords: "园艺 花卉 植物 flower garden plant", Icon: Flower2 },
  { id: "Sun", label: "阳光", group: "生活兴趣", keywords: "太阳 白天 天气 sun day weather", Icon: Sun },
  { id: "Moon", label: "月亮", group: "生活兴趣", keywords: "夜晚 睡眠 星空 moon night sleep", Icon: Moon },
  { id: "Mountain", label: "山峰", group: "生活兴趣", keywords: "登山 徒步 自然 mountain hiking nature", Icon: Mountain },
  { id: "Tent", label: "露营", group: "生活兴趣", keywords: "帐篷 野营 户外 tent camping outdoor", Icon: Tent },
  { id: "Plane", label: "旅行", group: "生活兴趣", keywords: "飞机 旅游 航班 plane travel flight", Icon: Plane },
  { id: "TrainFront", label: "火车", group: "生活兴趣", keywords: "高铁 铁路 交通 train railway transport", Icon: TrainFront },
  { id: "Bike", label: "骑行", group: "生活兴趣", keywords: "自行车 单车 运动 bike cycling bicycle", Icon: Bike },
  { id: "Car", label: "汽车", group: "生活兴趣", keywords: "驾驶 出行 自驾 car driving vehicle", Icon: Car },
  { id: "Gamepad2", label: "游戏", group: "生活兴趣", keywords: "手柄 娱乐 电竞 gamepad gaming esports", Icon: Gamepad2 },
  { id: "Dumbbell", label: "健身", group: "生活兴趣", keywords: "哑铃 运动 锻炼 dumbbell fitness workout", Icon: Dumbbell },
];

const iconsByName = new Map(
  folderIcons.map((option) => [option.id.toLowerCase(), option]),
);

const legacyAliases = new Map([
  ["code", "Code2"],
  ["development", "Code2"],
  ["design", "Palette"],
  ["ai", "Sparkles"],
  ["book", "BookOpen"],
  ["book-open", "BookOpen"],
  ["learning", "BookOpen"],
  ["lifestyle", "Coffee"],
  ["productivity", "Zap"],
  ["globe", "Globe2"],
]);

export function getFolderIcon(name?: string): FolderIconOption {
  const normalizedName = name?.trim().toLowerCase() ?? "folder";
  const canonicalName = legacyAliases.get(normalizedName) ?? normalizedName;
  return iconsByName.get(canonicalName.toLowerCase()) ?? folderIcons[0];
}

export function CategoryIcon({
  name,
  size = 18,
}: {
  name?: string;
  size?: number;
}) {
  const { Icon, id } = getFolderIcon(name);
  return <Icon size={size} aria-hidden="true" data-folder-icon={id} />;
}
